#!/bin/bash
echo "=== Havoc Railway Setup Guide ==="
echo ""
echo "مراحل راه‌اندازی Havoc روی Railway:"
echo ""
echo "1️⃣ فایل Havoc را به سرور Railway انتقال دهید:"
echo "   scp -r /home/ubu2/Havoc root@YOUR_RAILWAY_SERVER:/root/"
echo ""
echo "2️⃣ به سرور Railway متصل شوید:"
echo "   ssh root@YOUR_RAILWAY_SERVER"
echo ""
echo "3️⃣ وابستگی‌های لازم را نصب کنید:"
echo "   apt update && apt install -y nasm wget"
echo ""
echo "4️⃣ فایل‌های mingw را دانلود کنید:"
echo "   cd /root/Havoc"
echo "   ./teamserver/Install.sh"
echo ""
echo "5️⃣ Teamserver را در پس‌زمینه اجرا کنید:"
echo "   nohup ./havoc server --profile profiles/havoc.yaotl -v > havoc.log 2>&1 &"
echo ""
echo "6️⃣ برای اتصال Client از محل خود:"
echo "   - Host: آدرس IP سرور Railway"
echo "   - Port: 40056"
echo "   - User: 5pider"
echo "   - Password: password1234"
echo ""
echo "7️⃣ برای مشاهده لاگ:"
echo "   tail -f havoc.log"
echo ""
echo "8️⃣ برای متوقف کردن Teamserver:"
echo "   pkill -f './havoc server'"
echo ""
